---
version: '3.8'
services:
  nginx:
    image: "nginx:${NGINX_VERSION}"
    container_name: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    image: "percona:${PERCONA_VERSION}"
    container_name: db
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_project_manager
      - MYSQL_USER=go_user
      - MYSQL_PASSWORD=go_pw
    volumes:
      - percona:/var/lib/mysql
  cache:
    image: "redis:${REDIS_VERSION}"
    container_name: cache
    ports:
      - 6379:6379
    volumes:
      - ./_cache/redis:/data
  minio:
    image: "minio/minio:${MINIO_VERSION}"
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./_cache/minio:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: minio server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  redisinsight:
    image: "redislabs/redisinsight:${REDISINSIGHT_VERSION}"
    container_name: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
  adminer:
    image: "adminer:${ADMINER_VERSION}"
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080


volumes:
  redisinsight: {}
  percona: {}