---
version: '3.8'
services:
  nginx:
    image: "nginx:${NGINX_VERSION}"
    container_name: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
